### ISSUE TITLE
converting osm to sdf

### ISSUE THREAD

**Issue by ghost** [osrf/gazebo_osm#6]
hi
I want to convert a osm map, but it doesn't work 

``` bash
 ./gz_osm.py -O map.osm 
Downloading the osm data ... 
Elapsed time is 0.159263849258 seconds.
Extracting the map data for gazebo ...
Traceback (most recent call last):
  File "./gz_osm.py", line 175, in <module>
    roadPointWidthMap, modelPoseMap, buildingLocationMap = osmRoads.getMapDetails()
  File "source/osm2dict.py", line 308, in getMapDetails
    self.getModelDetails()
  File "source/osm2dict.py", line 195, in getModelDetails
    modelLocation = self.getPoints(coords)
  File "source/osm2dict.py", line 107, in getPoints
    dLat = lat2-np.radians(self.latStart)
TypeError: Not implemented for this type
```

**Comment by Tashwin** [comment]
Hi, 

I just fixed that bug and created a pull request regarding the same.
    https://github.com/osrf/gazebo_osm/pull/7
Hope it works out.
